### ISSUE TITLE
exec user process caused: exec format error

### ISSUE THREAD

**Issue by dukarm** [revoltchat/january#23]
Hello,

I try to run a self-hosted revolt server on my rpi4 arm64 but  the january container is the only one that does not start correctly.

I have this err: standard_init_linux.go:228: exec user process caused: exec format error

I think it comes from the arm64 arch, however I checked the compatibility on dockerhub before.

you will find attached my compose.

[docker-compose.txt](https://github.com/revoltchat/january/files/7853810/docker-compose.txt)

PS: Does this container have something to do with sending e-mail?

![image](https://user-images.githubusercontent.com/50875605/149124855-6960a78d-85c9-4d13-a594-802a2be86165.png)

I have no other idea where this error came from...

Best regards,

**Comment by insertish** [comment]
arm64 is not currently supported, tracked by https://github.com/revoltchat/backend/issues/142
